import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Particles } from "@/components/magicui/particles";

const Privacy = () => {
    return (
        <div className="min-h-screen w-full relative bg-black font-sans text-neutral-200">

            {/* Background Elements */}
            <div
                className="fixed top-0 left-0 w-full h-full z-0 pointer-events-none opacity-20"
                style={{
                    background: `
            radial-gradient(
              circle at top left,
              rgba(6, 182, 212, 0.1) 0%,
              rgba(0, 0, 0, 0) 50%
            )
          `,
                }}
            />
            <Particles
                className="fixed inset-0 z-0 opacity-30"
                quantity={50}
                ease={80}
                color="#ffffff"
                refresh
            />

            <div className="relative z-10 max-w-3xl mx-auto px-6 py-20">

                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5 }}
                    className="mb-12"
                >
                    <Link to="/" className="inline-flex items-center gap-2 text-neutral-500 hover:text-white transition-colors mb-8 group">
                        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                        Back to Home
                    </Link>
                    <h1 className="text-4xl font-bold text-white tracking-tight mb-4">Privacy Policy</h1>
                    <p className="text-neutral-500">Last updated: 2026-02-08</p>
                </motion.div>

                {/* Content */}
                <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: 0.1 }}
                    className="space-y-12 text-neutral-300 leading-relaxed"
                >
                    <div className="prose prose-invert max-w-none">
                        <p className="text-lg text-neutral-400">
                            ShareRoom is designed for temporary, account-free sharing.
                            This Privacy Policy explains what data is handled, how it is used, and the limits of the guarantees we provide.
                        </p>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">1. Overview</h2>
                            <p>
                                ShareRoom allows users to create temporary rooms to chat and share files without creating an account.
                                We intentionally minimize data collection and retain information only for the duration required to operate the service.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">2. Information We Do Not Collect</h2>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>User accounts or logins</li>
                                <li>Email addresses</li>
                                <li>Names or profile information</li>
                                <li>Payment information</li>
                                <li>Persistent identifiers tied to a real-world identity</li>
                            </ul>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">3. Information We Do Handle</h2>
                            <div className="space-y-4">
                                <div>
                                    <h3 className="text-base font-medium text-white mb-2">a. Session Identifiers</h3>
                                    <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                        <li>A session identifier is generated by the client for the duration of use.</li>
                                        <li>This identifier is not linked to a verified identity.</li>
                                        <li>It is used only to manage participation within a room and basic abuse prevention.</li>
                                    </ul>
                                </div>
                                <div>
                                    <h3 className="text-base font-medium text-white mb-2">b. Room Data</h3>
                                    <p className="mb-2">While a room is active, the system processes:</p>
                                    <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                        <li>Room metadata (room code, creation time, expiry time)</li>
                                        <li>Messages sent within the room</li>
                                        <li>Files shared within the room</li>
                                    </ul>
                                    <p className="mt-2 text-neutral-400">This data is accessible only while the room is active.</p>
                                </div>
                            </div>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">4. Data Expiry and Access Revocation</h2>
                            <p>Rooms are temporary by design. Each room has a fixed expiration time.</p>
                            <p>After a room expires:</p>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>Messages and shared files become inaccessible through the application.</li>
                                <li>API access to expired data is blocked at the database level.</li>
                                <li>Expired data is removed automatically as part of routine cleanup processes.</li>
                            </ul>
                            <p className="text-emerald-400/80 italic">ShareRoom guarantees time-bounded access, not permanent storage.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">5. Data Retention</h2>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>ShareRoom does not provide long-term data storage.</li>
                                <li>Data is retained only for the operational lifetime of a room.</li>
                                <li>Physical deletion may occur asynchronously after expiry as part of storage cleanup.</li>
                                <li>Backup systems and infrastructure-level logs (managed by hosting providers) may retain data temporarily, outside the application’s control.</li>
                            </ul>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">6. Cookies and Tracking</h2>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>ShareRoom <span className="text-white">does not</span> use advertising cookies or third-party trackers.</li>
                                <li>Local browser storage may be used to maintain an active session during use of the service.</li>
                            </ul>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">7. Third-Party Services</h2>
                            <p>
                                ShareRoom relies on third-party infrastructure providers to operate (e.g., hosting and database services).
                                These providers process data only to the extent necessary to deliver the service and are subject to their own privacy and security obligations.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">8. Security</h2>
                            <p>We take reasonable measures to protect data while a room is active.</p>
                            <p>However, ShareRoom does not claim to provide:</p>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>Strong anonymity guarantees</li>
                                <li>Audited end-to-end encryption</li>
                                <li>Protection against a determined adversary</li>
                            </ul>
                            <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-red-200 text-sm">
                                Users should not use ShareRoom for highly sensitive or regulated information.
                            </div>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">9. Intended Use</h2>
                            <p>ShareRoom is designed for:</p>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>Short-lived conversations</li>
                                <li>Temporary file sharing</li>
                                <li>One-time collaboration</li>
                            </ul>
                            <p>It is not intended for permanent communication, record-keeping, or data archiving.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">10. Changes to This Policy</h2>
                            <p>
                                This Privacy Policy may be updated as the project evolves.
                                Material changes will be reflected by updating the “Last updated” date.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-semibold text-white">11. Contact</h2>
                            <p>For questions about this Privacy Policy or ShareRoom’s data handling:</p>
                            <ul className="list-disc pl-5 space-y-2 text-neutral-400">
                                <li>Email: privacy@shareroom.io</li>
                                <li>Project repository: <a href="https://github.com" target="_blank" rel="noreferrer" className="text-indigo-400 hover:text-indigo-300 underline">GitHub</a></li>
                            </ul>
                        </section>

                        <section className="pt-8 border-t border-white/10">
                            <p className="text-sm text-neutral-500 italic">
                                Final note: This Privacy Policy intentionally describes what ShareRoom actually enforces, not aspirational guarantees.
                            </p>
                        </section>
                    </div>
                </motion.div>
            </div>
        </div>
    );
};

export default Privacy;
